spring:
  profiles:
    active: local

  datasource:
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: commercium-group

  redis:
    host: localhost
    port: 6379

app:
  database:
    write:
      url: jdbc:postgresql://localhost:5432/commercium
      username: commercium_user
      password: password
    read:
      url: jdbc:postgresql://localhost:5433/commercium_read
      username: commercium_read_user
      password: password

  jwt:
    secret: your-256-bit-secret-key-here
    access-token-expiry: 3600
    refresh-token-expiry: 2592000

---
spring:
  config:
    activate:
      on-profile: test

  datasource:
    url: jdbc:h2:mem:testdb

  kafka:
    bootstrap-servers: ${spring.embedded.kafka.brokers}
